### PR TITLE
adding travis ci

### PR DESCRIPTION
**Pull request by chriseverty**
I have set-up a working travis-ci job for the project. In the go I have noticed and removed [two warnings](https://github.com/logsniffer/logsniffer/commit/109a1ccd234ddcaa2b02d374cc8681cd3ac7b2aa) that have been reported in the log.

In order to get the build running I needed to increase the width of the column `entry_id` in table `QRTZ_FIRED_TRIGGERS` ([[1]](https://github.com/logsniffer/logsniffer/commit/11e363ebe337d96260f65e39d04570e31b2ca6ae), [[2]](https://github.com/logsniffer/logsniffer/commit/d1570f5e216375d47635698b4795b01e1ce64dd0)). It would not build on the travis-ci VMs otherwise. Those seem to have a very long machine name, which appears to be used as part of the generated key.

In order to get it working for the main project these steps would be required
- sign up for travis-ci
- alter the [linked buid-status-image the README.md](https://github.com/logsniffer/logsniffer/commit/03b005e49f82f7d7884b74d9a1dbf46ea0d17122)

One thing I noted is that there is one really long running test: `CompoundLogReaderTest#testLongComposition`. It takes 10 of the 14 minutes build time. I assume that this is some sort of benchmark? Probably this one could be put into an according [jUnit category](https://github.com/junit-team/junit4/wiki/Categories) so that it [maybe excluded from CI builds](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludedGroups).

### CODE REVIEW

**Comment by mbok** [comment]
Wow, great job, thanks a lot! I'll merge the pull request in few days as soon I'm back from holidays.

**Comment by logsniffer** [comment]
@chriseverty May I ask you to to sign logsniffer's [Contributor License Agreement](http://www.logsniffer.com/wp-content/uploads/2016/06/cla.pdf) and to send it please to cla@logsniffer.com?
This is only required once, no matter how many contributions you make in the future. Thank you for helping with this unfortunate administrative requirement.

**Comment by chriseverty** [comment]
Hello Micheal,

please find the signed CLA attached. By the way I am a native German
speaker.
But I think discussions on Github should be kept in English, shouldn't
they? :)

**Comment by logsniffer** [comment]
Hi @chriseverty,

leider ist der Anhang nicht durchgekommen :-(
Ich denke, es wird von GitHub bei Benutzung der Mailantwortfunktion nicht unterstützt. Könntest du es bitte nochmal an cla@logsniffer.com schicken. Danke für die Mühe!

And now I switch better again to English :-)

**Pull request merged**
